#! /bin/sh

DEFAULT_DIST="altlinux"

if [ ! -d /sys/firmware/efi ]; then
	echo "Not booted in EFI mode, unable to update EFI GRUB"
	exit 0
fi

GRUB_SYSCONF=/etc/sysconfig/grub2

if [ ! -f "$GRUB_SYSCONF" ]; then
    echo "There is no $GRUB_SYSCONF, nothing to do"
    exit 0
fi

. "$GRUB_SYSCONF"

DIST="${GRUB_BOOTLOADER_DIST:-$DEFAULT_DIST}"
EFI_DIR="/boot/efi"
GRUB_CFG="$EFI_DIR/EFI/$DIST/grub.cfg"

if ! stat $EFI_DIR/EFI/$DIST/grub*.efi > /dev/null 2>&1; then
	echo "$EFI_DIR/EFI/$DIST/grub*.efi is missing, nothing to update."
	echo "Please run grub-install"
	exit 0
fi

case "$GRUB_AUTOUPDATE_FORCE" in
	true|yes) GRUB_FORCE="--force";;
esac

echo "Updating grub in $EFI_DIR"
grub-install $GRUB_FORCE --force-extra-removable
