#! /bin/sh

GRUB_SYSCONF=/etc/sysconfig/grub2

if [ ! -f "$GRUB_SYSCONF" ]; then
    echo "There is no $GRUB_SYSCONF, nothing to do"
    exit 0
fi

. "$GRUB_SYSCONF"

if [ -z "$GRUB_AUTOUPDATE_DEVICE" ] ; then
    echo "WARNING: GRUB_AUTOUPDATE_DEVICE not set in $GRUB_SYSCONF"
    echo "WARNING: run grub-install /dev/sdX if needed"
    exit 0
fi

GRUB_FORCE=""

case "$GRUB_AUTOUPDATE_FORCE" in
	true|yes) GRUB_FORCE="--force";;
esac

for dev in $GRUB_AUTOUPDATE_DEVICE; do
	echo "Updating grub on $dev"
	/usr/sbin/grub-install "$dev" $GRUB_FORCE
done
