#!/bin/sh

#Source functions library.
WITHOUT_RC_COMPAT=1
. /etc/init.d/functions
SourceIfExists /etc/sysconfig/i18n
export LANG

chmod +w /boot/grub/grub.cfg
action "Updating grub configuration:" grub-mkconfig -o /boot/grub/grub.cfg

